name: Build Image on PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  build-image:
    uses: tkhom3/gha-workflows/.github/workflows/build-image-pr.yml@aa66c6cf2188919b4e79194010e779c6c6833b27 # v1.0.13
